language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
gemfile:
- Gemfile
cache: bundler
addons:
  code_climate:
    repo_token: 4f4ebba901d347fd41f502bceab32b2b0d71eda489b74eb7d5c354d41667dcb2
script: "REPORT_CODE_CLIMATE=true bundle exec rake"
